<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModuloSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Deshabilitar verificación de foreign keys temporalmente
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Limpiar tabla de módulos existentes
        DB::table('modulo')->truncate();

        // Habilitar verificación de foreign keys nuevamente
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $modulos = [
            // ========== DASHBOARD ==========
            [
                'id' => 1,
                'nombre' => 'Dashboard',
                'icono' => 'ki-filled ki-home',
                'ruta' => '/',
                'id_padre' => null,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== CONFIGURACIÓN ==========
            [
                'id' => 2,
                'nombre' => 'Configuración',
                'icono' => 'ki-filled ki-setting-2',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'nombre' => 'Empresa',
                'icono' => 'ki-filled ki-shop',
                'ruta' => '/company',
                'id_padre' => 2,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'nombre' => 'Almacenes',
                'icono' => 'ki-filled ki-home',
                'ruta' => '/warehouse',
                'id_padre' => 2,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'nombre' => 'Módulos',
                'icono' => 'ki-filled ki-category',
                'ruta' => '/module',
                'id_padre' => 2,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'nombre' => 'Roles',
                'icono' => 'ki-filled ki-security-user',
                'ruta' => '/setting/rol',
                'id_padre' => 2,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 7,
                'nombre' => 'Usuarios',
                'icono' => 'ki-filled ki-profile-user',
                'ruta' => '/setting/users',
                'id_padre' => 2,
                'is_padre' => false,
                'orden' => 5,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== CATÁLOGOS GENERALES ==========
            [
                'id' => 10,
                'nombre' => 'Catálogos',
                'icono' => 'ki-filled ki-book',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'nombre' => 'Grupos de Categorías',
                'icono' => 'ki-filled ki-category',
                'ruta' => '/category-groups',
                'id_padre' => 10,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'nombre' => 'Subcategorías',
                'icono' => 'ki-filled ki-subtitle',
                'ruta' => '/sub-category',
                'id_padre' => 10,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'nombre' => 'Marcas',
                'icono' => 'ki-filled ki-tag',
                'ruta' => '/brands',
                'id_padre' => 10,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'nombre' => 'Cargos',
                'icono' => 'ki-filled ki-briefcase',
                'ruta' => '/jobtitles',
                'id_padre' => 10,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== CATÁLOGOS HACIENDA ==========
            [
                'id' => 20,
                'nombre' => 'Catálogos Hacienda',
                'icono' => 'ki-filled ki-bank',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'nombre' => 'Condiciones de Operación',
                'icono' => 'ki-filled ki-check-circle',
                'ruta' => '/operation-condition',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'nombre' => 'Métodos de Pago',
                'icono' => 'ki-filled ki-credit-card',
                'ruta' => '/payment-methods',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'nombre' => 'Documentos Tributarios',
                'icono' => 'ki-filled ki-file',
                'ruta' => '/cat-doc-tributario',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'nombre' => 'Actividades Económicas',
                'icono' => 'ki-filled ki-chart-line-up',
                'ruta' => '/economic-activities',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 25,
                'nombre' => 'Unidades de Medida',
                'icono' => 'ki-filled ki-chart-simple',
                'ruta' => '/unit-measurements',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 5,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'nombre' => 'Ambiente Destino',
                'icono' => 'ki-filled ki-setting',
                'ruta' => '/cat-ambiente-destino',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 6,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'nombre' => 'Países',
                'icono' => 'ki-filled ki-flag',
                'ruta' => '/countries',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 7,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'nombre' => 'Departamentos',
                'icono' => 'ki-filled ki-map',
                'ruta' => '/departments',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 8,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'nombre' => 'Municipios',
                'icono' => 'ki-filled ki-geolocation',
                'ruta' => '/municipalities',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 9,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'nombre' => 'Distritos',
                'icono' => 'ki-filled ki-location',
                'ruta' => '/districts',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 10,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'nombre' => 'Tipos de Documento Cliente',
                'icono' => 'ki-filled ki-badge',
                'ruta' => '/cat-customer-doc-types',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 11,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 32,
                'nombre' => 'Tipos de Cliente',
                'icono' => 'ki-filled ki-people',
                'ruta' => '/customer-types',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 12,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'nombre' => 'Tipos de Establecimiento',
                'icono' => 'ki-filled ki-home-2',
                'ruta' => '/stablishment-types',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 13,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 34,
                'nombre' => 'Tipos de Contingencia',
                'icono' => 'ki-filled ki-shield-cross',
                'ruta' => '/contingency-types',
                'id_padre' => 20,
                'is_padre' => false,
                'orden' => 14,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== PROVEEDORES ==========
            [
                'id' => 40,
                'nombre' => 'Proveedores',
                'icono' => 'ki-filled ki-shop',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 5,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 41,
                'nombre' => 'Tipos de Proveedor',
                'icono' => 'ki-filled ki-category',
                'ruta' => '/providers-types',
                'id_padre' => 40,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 42,
                'nombre' => 'Tipos de Documento',
                'icono' => 'ki-filled ki-document',
                'ruta' => '/providers-documents-types',
                'id_padre' => 40,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 43,
                'nombre' => 'Lista de Proveedores',
                'icono' => 'ki-filled ki-profile-user',
                'ruta' => '/providers',
                'id_padre' => 40,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 44,
                'nombre' => 'Direcciones',
                'icono' => 'ki-filled ki-geolocation',
                'ruta' => '/provider-addresses',
                'id_padre' => 40,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== CLIENTES ==========
            [
                'id' => 50,
                'nombre' => 'Clientes',
                'icono' => 'ki-filled ki-people',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 6,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 51,
                'nombre' => 'Lista de Clientes',
                'icono' => 'ki-filled ki-profile-user',
                'ruta' => '/customers',
                'id_padre' => 50,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 52,
                'nombre' => 'Direcciones',
                'icono' => 'ki-filled ki-geolocation',
                'ruta' => '/customer-addresses',
                'id_padre' => 50,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== EMPLEADOS ==========
            [
                'id' => 60,
                'nombre' => 'Empleados',
                'icono' => 'ki-filled ki-user',
                'ruta' => '/employees',
                'id_padre' => null,
                'is_padre' => false,
                'orden' => 7,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== PRODUCTOS ==========
            [
                'id' => 70,
                'nombre' => 'Productos',
                'icono' => 'ki-filled ki-package',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 8,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 71,
                'nombre' => 'Lista de Productos',
                'icono' => 'ki-filled ki-category',
                'ruta' => '/products',
                'id_padre' => 70,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 72,
                'nombre' => 'Equivalencias',
                'icono' => 'ki-filled ki-arrows-loop',
                'ruta' => '/equivalents',
                'id_padre' => 70,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 73,
                'nombre' => 'Intercambios',
                'icono' => 'ki-filled ki-shuffle',
                'ruta' => '/interchanges',
                'id_padre' => 70,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 74,
                'nombre' => 'Lotes',
                'icono' => 'ki-filled ki-calendar',
                'ruta' => '/lotes',
                'id_padre' => 70,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 75,
                'nombre' => 'Orígenes de Código de Lote',
                'icono' => 'ki-filled ki-code',
                'ruta' => '/batch-code-origins',
                'id_padre' => 70,
                'is_padre' => false,
                'orden' => 5,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== INVENTARIO ==========
            [
                'id' => 80,
                'nombre' => 'Inventario',
                'icono' => 'ki-filled ki-cube',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 9,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 81,
                'nombre' => 'Inventario General',
                'icono' => 'ki-filled ki-chart-simple-2',
                'ruta' => '/inventory',
                'id_padre' => 80,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 82,
                'nombre' => 'Inventarios por Lote',
                'icono' => 'ki-filled ki-calendar-tick',
                'ruta' => '/inventory/batches',
                'id_padre' => 80,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 83,
                'nombre' => 'Historial de Costos',
                'icono' => 'ki-filled ki-chart-line-down',
                'ruta' => '/cost-history',
                'id_padre' => 80,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 84,
                'nombre' => 'Kardex',
                'icono' => 'ki-filled ki-note-2',
                'ruta' => '/kardex',
                'id_padre' => 80,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== PARQUE VEHICULAR ==========
            [
                'id' => 90,
                'nombre' => 'Parque Vehicular',
                'icono' => 'ki-filled ki-truck',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 10,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 91,
                'nombre' => 'Tipos de Placa',
                'icono' => 'ki-filled ki-tablet',
                'ruta' => '/plate-types',
                'id_padre' => 90,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 92,
                'nombre' => 'Modelos de Vehículos',
                'icono' => 'ki-filled ki-car',
                'ruta' => '/vehicle-models',
                'id_padre' => 90,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 93,
                'nombre' => 'Tipos de Combustible',
                'icono' => 'ki-filled ki-flash',
                'ruta' => '/fuel-types',
                'id_padre' => 90,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 94,
                'nombre' => 'Vehículos',
                'icono' => 'ki-filled ki-truck',
                'ruta' => '/vehicles',
                'id_padre' => 90,
                'is_padre' => false,
                'orden' => 4,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 95,
                'nombre' => 'Aplicaciones',
                'icono' => 'ki-filled ki-setting-2',
                'ruta' => '/applications',
                'id_padre' => 90,
                'is_padre' => false,
                'orden' => 5,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== COMPRAS ==========
            [
                'id' => 100,
                'nombre' => 'Compras',
                'icono' => 'ki-filled ki-basket',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 11,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 101,
                'nombre' => 'Compras',
                'icono' => 'ki-filled ki-shop',
                'ruta' => '/purchases',
                'id_padre' => 100,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 102,
                'nombre' => 'Cotizaciones',
                'icono' => 'ki-filled ki-questionnaire-tablet',
                'ruta' => '/quote-purchases',
                'id_padre' => 100,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== VENTAS ==========
            [
                'id' => 110,
                'nombre' => 'Ventas',
                'icono' => 'ki-filled ki-dollar',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 12,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 111,
                'nombre' => 'Lista de Ventas',
                'icono' => 'ki-filled ki-file',
                'ruta' => '/sales',
                'id_padre' => 110,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 112,
                'nombre' => 'Nueva Venta',
                'icono' => 'ki-filled ki-add-files',
                'ruta' => '/sales/add',
                'id_padre' => 110,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 113,
                'nombre' => 'Detalles de Pago',
                'icono' => 'ki-filled ki-credit-card',
                'ruta' => '/sales/payments',
                'id_padre' => 110,
                'is_padre' => false,
                'orden' => 3,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== FACTURACIÓN ELECTRÓNICA ==========
            [
                'id' => 120,
                'nombre' => 'Facturación Electrónica',
                'icono' => 'ki-filled ki-document',
                'ruta' => '#',
                'id_padre' => null,
                'is_padre' => true,
                'orden' => 13,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 121,
                'nombre' => 'Historial de DTEs',
                'icono' => 'ki-filled ki-file-sheet',
                'ruta' => '/dte/history',
                'id_padre' => 120,
                'is_padre' => false,
                'orden' => 1,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
            [
                'id' => 122,
                'nombre' => 'Contingencias',
                'icono' => 'ki-filled ki-shield-cross',
                'ruta' => '/contingencies',
                'id_padre' => 120,
                'is_padre' => false,
                'orden' => 2,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],

            // ========== REPORTES ==========
            [
                'id' => 130,
                'nombre' => 'Reportes',
                'icono' => 'ki-filled ki-chart-simple',
                'ruta' => '/reports',
                'id_padre' => null,
                'is_padre' => false,
                'orden' => 14,
                'is_minimazed' => false,
                'target' => '_self',
                'is_active' => true,
            ],
        ];

        foreach ($modulos as $modulo) {
            DB::table('modulo')->insert($modulo);
        }

        $this->command->info('✅ Módulos creados exitosamente: ' . count($modulos) . ' módulos registrados');
    }
}
